### ISSUE TITLE
commands to manage connection history

### ISSUE THREAD

**Issue by arnellebalane** [arnellebalane/wifi-cli#1]
In the case of `nmcli` for Linux, it remembers all the networks that it has connected to in the past. This issue is about adding a couple of commands which will make wifi-cli forget about those networks.
- [ ] **`wf history`** (alias: **`wf h`**): list the items in the connection history. might be equivalent to running `nmcli connection list`, but items should be indexed by a number for easier reference in future commands.
- [ ] **`wf forget <index|ssid>`** (alias: **`wf f <index|ssid>`**): removes the network with the given `ssid` or `index` (which is based on the `history` command) from the connection history.
- [ ] **`wf forget`** (alias: **`wf f`**): forgets all the networks in the connection history.

**Comment by jonathas** [comment]
I'm on it :+1:

**Comment by arnellebalane** [comment]
@jonathas awesome, thanks! :+1:

**Comment by jonathas** [comment]
done :+1:
